#!/usr/bin/env python3

import sys
import errno
import json
import os

# check if args are correct
if len(sys.argv) != 2:
    sys.exit(-errno.EINVAL)


conf_path = '/tmp/hyperfocal_backend_state.json'

# load internal config
with open(conf_path, 'r') as f:
    data = json.loads(f.read())

# check if the requested device is present
if sys.argv[1] not in data:
    sys.exit(-errno.ENODEV)

# TODO: actually do device cleanup...

sys.exit(0)
