#!/usr/bin/env python3

import sys
import errno
import json
# import v4l2
# import fcntl
# import os

# check if args are correct
if len(sys.argv) == 1:
    print(
        json.dumps({
            "name": "lazy-back-end-example",
            "version": "0.1",
            "description": "A lazy back end example, long description, blah blah blah blah blah blah blah, etc.",
            "author": "Oleg Vorobiov <oleg.vorobiov@somainline.org>",
            "maintainer": "Oleg Vorobiov <oleg.vorobiov@somainline.org>"
        })
    )
    sys.exit(0)

if len(sys.argv) > 2:
    sys.exit(-errno.EINVAL)


conf_path = '/tmp/hyperfocal_backend_state.json'

# load internal config
with open(conf_path, 'r') as f:
    data = json.loads(f.read())

# check if the requested device is present
if sys.argv[1] not in data:
    sys.exit(-errno.ENODEV)


# TODO: fix the output format and output meaningful data


# with open(data[sys.argv[1]], 'w') as vd:
#     cp = v4l2.v4l2_capability()
#     fcntl.ioctl(vd, v4l2.VIDIOC_QUERYCAP, cp)
    # print(cp.driver)
    # print(cp.card)
    # print(cp._fields_)

print(json.dumps({'rotate': 0}))

sys.exit(0)
